// src/app/app.component.ts
import { Component } from '@angular/core';

import { APP_TITLE } from './constants/title';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  APP_TITLE = APP_TITLE;
}

<div class="text-center">
  <h1 class="font-bold my-8 text-3xl text-black">{{ APP_TITLE }}</h1>

  <router-outlet></router-outlet>
</div>

// src/App.vue
<script setup lang="ts">
import { RouterView } from 'vue-router'

import { APP_TITLE } from '@/constants/title'
</script>

<template>
  <metainfo>
    <template v-slot:title="{ content }">{{ content ?? APP_TITLE }}</template>
  </metainfo>

  <div class="text-center">
    <h1 class="font-bold my-8 text-3xl text-black">{{ APP_TITLE }}</h1>

    <RouterView />
  </div>
</template>
